language: java
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8

install: ./gradlew setupCiWorkspace -S
script: ./gradlew build

env:
  global:
    TERM=dumb
    
notifications:
  email: false
  irc: "irc.esper.net#railcraft"
